import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import AuthProvider from "./context/AuthProvider";
import { ToastProvider } from "@/components/ui/custom-toast"; // 👈 Import custom toast
import { LoadingProvider } from "@/app/context/LoadingContext";
import AppWrapper from "@/components/AppWrapper";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Katalyst",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={spaceGrotesk.variable}>
      <body className="antialiased">
        <AuthProvider>
          <LoadingProvider>
            <ToastProvider> {/* 👈 Add ToastProvider here */}
              <AppWrapper>
                {children}
              </AppWrapper>
            </ToastProvider>
          </LoadingProvider>
        </AuthProvider>
        {/* 👇 Remove old Toaster - not needed anymore */}
        {/* <Toaster /> */}
      </body>
    </html>
  );
}